##################################################
###       Configuration for GuestUnlock!       ###
##################################################
#
# Guest section: Options for Guests(player with perm: guestunlock.guest) #
    # JoinMessage: Message displayed for guest when they join #
    # Message: Message displayed at the specifyed interval for guests #
    # MessageInterval: Interval the Message is displayed at #
##########
# Admin section: Options for the plugins functionality #
    # Password: The correct password #
    # Debug: Debug? #
    # CheckForPass: Wether to check for the password in chat-messages? And if it is there remove it #
    # CheckForUpdate: Check for updates?
##########    
# PermissionSystem section: Options for various permissionplugins support #
    # Vault: 
        # Enable: Use Vault? (If false, automatic group-moving will NOT work)
        # BuildGroup: Groupname for your build-group, a player that enters the correct password will be moved to this group if "Enable" is true
        # UseSpecificWorld: If true, GuestUnlock will add the player to "BuildGroup" only in the "main-world". Must be true for plugins like bPermissions.
Guest:
    JoinMessage: Welcome Guest, please read the rules, then send the password /guestunlock <password>
    Message: Welcome Guest, please read the rules, then send the password /guestunlock <password>
    MessageInterval: 30

Admin:
    Password: guestunlock
    Debug: false
    CheckForPass: false
    CheckForUpdate: true
PermissionSystem:
    Vault:
        Enable: true
        BuildGroup: builder
        UseSpecificWorld: true
