##################################################
###       Configuration for GuestUnlock!       ###
##################################################
# 
# For information on how to configure this pluign please see 
# http://dev.bukkit.org/server-mods/guestunlock/pages/configuration
#
##################################################
Guest:
    JoinMessage: Welcome Guest, please read the rules, then send the password /guestunlock <password>
    Message: Welcome Guest, please read the rules, then send the password /guestunlock <password>
    MessageInterval: 30
Admin:
    Password: guestunlock
    Debug: false
    CheckForPass: false
    CheckForUpdate: true
PermissionSystem:
    Vault:
        Enable: true
        BuildGroup: builder
        UseSpecificWorld: true
        RemoveOldGroup: false
