##################################################
###       Configuration for GuestUnlock!       ###
##################################################
#
# Guest section: Options for Guests(player with perm: guestunlock.guest) #
    # JoinMessage: Message displayed for guest when they join #
    # Message: Message displayed at the specifyed interval for guests #
    # MessageInterval: Interval the Message is displayed at #
##########
# Admin section: Options for the plugins functionality #
    # Password: The correct password #
    # Debug: Debug? #
    # CheckForPass: Wether to check for the password in chat-messages? And if it is there remove it #
##########    
# PermissionSystem section: Options for various permissionplugins support #
    # PEX/GM/BP #
        # Enable: Enable the auto-moving for that perm-plugin? #
        # BuildGroup: Which group the player is being moved to? #
Guest:
    JoinMessage: Welcome Guest, please read the rules, then send the password /guestunlock <password>
    Message: Welcome Guest, please read the rules, then send the password /guestunlock <password>
    MessageInterval: 30

Admin:
    Password: guestunlock
    Debug: false
    CheckForPass: false
PermissionSystem:
    PermissionsEx:
        Enable: false
        BuildGroup: builder
    GroupManager:
        Enable: false
        BuildGroup: Builder
    bPermissions:
        Enable: false 
        BuildGroup: builder
